// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tasked.Data;

#nullable disable

namespace Tasked.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613025533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tasked.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_name");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Tasked.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<int>("IssueCount")
                        .HasColumnType("integer")
                        .HasColumnName("issue_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_projects_org_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Tasked.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Tasked.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IssueNo")
                        .HasColumnType("integer")
                        .HasColumnName("issue_no");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.HasIndex("AssignedId")
                        .HasDatabaseName("ix_todos_assigned_id");

                    b.HasIndex("ProjectId", "IssueNo")
                        .IsUnique()
                        .HasDatabaseName("ix_todos_project_id_issue_no");

                    b.ToTable("todos", (string)null);
                });

            modelBuilder.Entity("Tasked.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_users_org_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tasked.Entities.Project", b =>
                {
                    b.HasOne("Tasked.Entities.Organization", "Org")
                        .WithMany("Projects")
                        .HasForeignKey("OrgId")
                        .HasConstraintName("fk_projects_organizations_org_id");

                    b.HasOne("Tasked.Entities.User", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_owner_id");

                    b.Navigation("Org");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Tasked.Entities.ProjectMember", b =>
                {
                    b.HasOne("Tasked.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("Tasked.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tasked.Entities.Todo", b =>
                {
                    b.HasOne("Tasked.Entities.User", "Assigned")
                        .WithMany("AssignedTodos")
                        .HasForeignKey("AssignedId")
                        .HasConstraintName("fk_todos_users_assigned_id");

                    b.HasOne("Tasked.Entities.Project", "Project")
                        .WithMany("Todos")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todos_projects_project_id");

                    b.Navigation("Assigned");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tasked.Entities.User", b =>
                {
                    b.HasOne("Tasked.Entities.Organization", "Org")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .HasConstraintName("fk_users_organizations_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Tasked.Entities.Organization", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Tasked.Entities.Project", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("Tasked.Entities.User", b =>
                {
                    b.Navigation("AssignedTodos");

                    b.Navigation("OwnedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
